version: "3"
services: 
  elixir:
    build: ./
    volumes: 
      - ./:/code
    working_dir: /code
    ports: 
      - 4000:4000
    environment: 
      CHOKIDAR_USEPOLLING: "true"
      MIX_BUILD_PATH: /tmp/build
    stdin_open: true
    tty: true
    command: mix phx.server